### ISSUE TITLE
Cross-origin request fails in browser due to preflighting

### ISSUE THREAD

**Issue by co60ca** [klahnakoski/ActiveData#2]
Since Flask uses whitelisting for HTTP methods ActiveData doesn't respond correctly to CORS protections that come from a browser that attempt to preflight the request. Namely ActiveData doesn't include the OPTIONS method in its catchall route. 

CORS headers are new to me so this is my source:
https://stackoverflow.com/questions/1256593/why-am-i-getting-an-options-request-instead-of-a-get-request#13030629

Curl script generated from my browser that reproduces the issue:
```
curl 'http://activedata.allizom.org/query' -X OPTIONS -H 'Pragma: no-cache' -H 'Access-Control-Request-Method: POST' -H 'Origin: http://localhost:8080' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Referer: http://localhost:8080/' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Access-Control-Request-Headers: content-type' --compressed -I
```

Gives you a response headers of 
```
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 14 Oct 2016 07:52:06 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
``` 
Which as you can tell does not contain the "Access-Control-Allow-Origin" header which is entered [on this line](https://github.com/klahnakoski/ActiveData/blob/dev/active_data/app.py#L62)

I believe the patch needs to be made to the [accepted HTTP methods for this route](https://github.com/klahnakoski/ActiveData/blob/dev/active_data/app.py#L53).

It may also be worth adding all the rest of the well known headers to the catch all at the same time:
http://flask.pocoo.org/docs/0.11/quickstart/#routing

LASTLY:
You get style points if you change the header to "Access-Control-Allow-Origin"

I would have wrote the patch myself but I'm not sure just adding OPTIONS is going to be sufficient and I wont be able to test the code on my side.

**Comment by klahnakoski** [comment]
The following change has been made, and pushed to production: https://github.com/klahnakoski/ActiveData/commit/7c031e35c4ce646ee2e5a7afb3f44158ac354314

Please confirm if it behaves as you expect.

Thank you!

**Comment by co60ca** [comment]
Mostly good! Will work for now
