### ISSUE TITLE
 python27 active_data/app.py --settings=resources/config/simple_settings.json - raises err in ElasticSearch 5.2.2

### ISSUE THREAD

**Issue by maggienj** [klahnakoski/ActiveData#7]
<deltd>

**Comment by maggienj** [comment]
Have been trying different combinations.

this is the current combination and the ES 5.2.2 is up and running.

```
script.engine.groovy.inline: true
#script.engine.groovy.update: true
script.engine.groovy.stored: true
#script.indexed: on
http.compression: true
cluster.name: maggie_dev

```


Still this command raises the following set of errs.
$ python27 active_data/app.py --settings=resources/config/simple_settings.json
kabalidaa - 2017-04-09 01:22:47 - Main Thread - "threads.py:499" (join) - "Main Thread" waiting on thread "log thread"
kabalidaa - 2017-04-09 01:22:47 - log to stream - "threads.py:474" (_run) - thread "log to stream" stopping
kabalidaa - 2017-04-09 01:22:47 - Main Thread - "threads.py:485" (_run) - thread "log to stream" is done
Traceback (most recent call last):
  File "active_data/app.py", line 192, in <module>
    setup()
  File "active_data/app.py", line 125, in setup
    Log.error("Serious problem with ActiveData service construction!  Shutdown!", cause=e)
  File "C:\ActiveData\pyLibrary\debugs\logs.py", line 375, in error
    raise e
pyLibrary.debugs.exceptions.Except: ERROR: Serious problem with ActiveData service construction!  Shutdown!
        File "active_data/app.py", line 125, in setup
        File "active_data/app.py", line 192, in <module>
caused by
        ERROR: Problem with call to http://localhost:9200/active_data_requests20170409_012246
{"mappings": {"request_log": {"properties": {"content_length": {"index": "not_analyzed", "type": "string"}, "http_user_agent": {"index": "not_analyzed", "type": "string"}, "from": {"index": "not_analyzed", "type": "string"}, "remote_addr": {"index": "not_analyzed", "type": "string"}, "timestamp": {"type": "double"}, "error": {"type": "object", "enabled": false, "store": "yes", "index": "no"}, "query": {"type": "object", "enabled": false, "store": "yes", "index": "no"}, "path": {"index": "not_analyzed", "type": "string"}, "data": {"index": "not_analyzed", "type": "string"}, "http_accept_encoding": {"index": "not_analyzed", "type": "string"}}, "dynamic_templates": [{"default_strings": {"match_mapping_type": "string", "mapping": {"index": "not_analyzed", "type": "string"}, "match": "*"}}], "_source": {"compress": true}}}, "settings": {"index": {"number_of_replicas": 0, "store": {"throttle": {"max_bytes_per_sec": "2mb", "type": "merge"}}, "number_of_shards": 3}}}
        File "C:\ActiveData\pyLibrary\env\elasticsearch.py", line 760, in post
        File "C:\ActiveData\pyLibrary\env\elasticsearch.py", line 635, in create_index
        File "C:\ActiveData\pyLibrary\meta.py", line 140, in wrapper
        File "C:\ActiveData\pyLibrary\env\elasticsearch.py", line 509, in get_or_create_index
        File "C:\ActiveData\pyLibrary\meta.py", line 144, in wrapper
        File "active_data/app.py", line 97, in setup
        File "active_data/app.py", line 192, in <module>
caused by
        ERROR: Bad Request: No handler found for uri [/active_data_requests20170409_012246] and method [POST]
        File "C:\ActiveData\pyLibrary\env\elasticsearch.py", line 738, in post
        File "C:\ActiveData\pyLibrary\env\elasticsearch.py", line 635, in create_index
        File "C:\ActiveData\pyLibrary\meta.py", line 140, in wrapper
        File "C:\ActiveData\pyLibrary\env\elasticsearch.py", line 509, in get_or_create_index
        File "C:\ActiveData\pyLibrary\meta.py", line 144, in wrapper
        File "active_data/app.py", line 97, in setup
        File "active_data/app.py", line 192, in <module>

**Comment by maggienj** [comment]
`http://localhost:9200/active_data_requests20170409_012246`

results in... 

{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"active_data_requests20170409_012246","index_uuid":"_na_","index":"active_data_requests20170409_012246"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"active_data_requests20170409_012246","index_uuid":"_na_","index":"active_data_requests20170409_012246"},"status":404}

**Comment by klahnakoski** [comment]
It appears the POST might be the problem:

    ERROR: Bad Request: No handler found for uri [/active_data_requests20170409_012246] and method [POST]

Looking at the stack trace it appears the code is attempting to make an index:

    File "C:\ActiveData\pyLibrary\env\elasticsearch.py", line 635, in create_index

Then I Google how to "create index in elasticsearch" and find this URL https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html

...and the example shows a PUT command is required to make an index.

In general, this is the problem with upgrading to ES5+:  The old versions of ES were very flexible on accepting commands and data.  These newer versions are very strict.  Little adjustments like PUT vs POST are important for getting things to run.

**Comment by maggienj** [comment]
I see.... 
source: https://discuss.elastic.co/t/when-to-use-put-versus-post/68550/2
It's all about REST semantics.
POST basically that you are posting a request which is going to modify the server state.
```
POST index/type
{
  "foo": "bar"
}
```

will generate an _id server side and will index the document with this _id.
PUT is used to send a resource to the server.
```
PUT index/type/id
{
  "foo": "bar"
}
```

will put or update a document named index/type/id in the server.

Makes sense?
More details here: https://en.wikipedia.org/wiki/Representational_state_transfer2

Now, we need to check which file uses "POST" and then try to replace it with "PUT"

**Comment by maggienj** [comment]
Just ran a search in the ActiveData directory and these files have the word POST in it.

active_data/app.py:app.add_url_rule('/query', None, query, defaults={'path': ''}, methods=['GET', 'POST'])
active_data/app.py:app.add_url_rule('/query/', None, query, defaults={'path': ''}, methods=['GET', 'POST'])
active_data/app.py:app.add_url_rule('/query/<path:path>', None, query, defaults={'path': ''}, methods=['GET', 'POST'])
active_data/app.py:@app.route('/', defaults={'path': ''}, methods=['GET', 'POST'])
active_data/public/lib/ccc/cdf/jquery.js:"string")return zb.call(this,a);else if(!this.length)return this;var f=a.indexOf(" ");if(f>=0){var e=a.slice(f,a.length);a=a.slice(0,f)}f="GET";if(b)if(c.isFunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);f="POST"}var j=this;c.ajax({url:a,type:f,dataType:"html",data:b,complete:function(i,o){if(o==="success"||o==="notmodified")j.html(e?c("<div />").append(i.responseText.replace(tb,"")).find(e):i.responseText);d&&j.each(d,[i.responseText,o,i])}});return this},
active_data/public/lib/ccc/cdf/jquery.js:function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b=null}return c.ajax({type:"GET",url:a,data:b,success:d,dataType:f})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b={}}return c.ajax({type:"POST",url:a,data:b,success:d,dataType:f})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,
active_data/public/lib/ccc/cdf/jquery.js:g("abort")}}catch(l){}e.async&&e.timeout>0&&setTimeout(function(){x&&!E&&g("timeout")},e.timeout);try{x.send(n==="POST"||n==="PUT"||n==="DELETE"?e.data:null)}catch(m){c.handleError(e,x,null,m);d()}e.async||g();return x}},handleError:function(a,b,d,f){if(a.error)a.error.call(a.context||a,b,d,f);if(a.global)(a.context?c(a.context):c.event).trigger("ajaxError",[b,a,f])},active:0,httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===
active_data/public/lib/jquery-ui/js/jquery-1.9.1.js:            type = "POST";
active_data/public/lib/jquery.js:               type = "POST";
active_data/public/modevlib/rest/BugzillaClient.js:    this.APIRequest('/bug', 'POST', callback, 'ref', bug);
active_data/public/modevlib/rest/BugzillaClient.js:    this.APIRequest('/bug/' + id + '/comment', 'POST', callback, 'ref', comment);
active_data/public/modevlib/rest/BugzillaClient.js:    this.APIRequest('/bug/' + id + '/attachment', 'POST', callback, 'ref', attachment);
active_data/public/modevlib/rest/Rest.js:  if (ajaxParam.type===undefined) ajaxParam.type="POST";
active_data/public/modevlib/rest/Rest.js:  ajaxParam.type="POST";
Binary file docs/ActiveData Lightning 150910.ppt matches
Binary file docs/ActiveData Lightning 160613.ppt matches
Binary file docs/ActiveData Summary 150323.ppt matches
pyLibrary/env/elasticsearch.py:                Log.note("POST {{url}}", url=url)
Binary file pyLibrary/env/elasticsearch.pyc matches
pyLibrary/vendor/sqlite/sqlite3.h:#define SQLITE_TESTCTRL_IMPOSTER                25
README.md:      curl -XPOST -d "{\"from\":\"unittest\"}" http://activedata.allizom.org/query
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"cancel\": {\"index\": \"unittest20160729_131157\",\"shard\": 79, \"node\":\"primary\", \"allow_primary\":true}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"cancel\": {\"index\": \"unittest20160810_175547\",\"shard\": 4, \"node\":\"secondary\", \"allow_primary\":true}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"cancel\": {\"index\": \"unittest20160810_175547\",\"shard\": 26, \"node\":\"secondary\", \"allow_primary\":true}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"cancel\": {\"index\": \"unittest20160810_175547\",\"shard\": 31, \"node\":\"secondary\", \"allow_primary\":true}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"cancel\": {\"index\": \"unittest20160810_175547\",\"shard\": 33, \"node\":\"secondary\", \"allow_primary\":true}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"cancel\": {\"index\": \"unittest20160810_175547\",\"shard\": 39, \"node\":\"secondary\", \"allow_primary\":true}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"cancel\": {\"index\": \"unittest20160810_175547\",\"shard\": 69, \"node\":\"secondary\", \"allow_primary\":true}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"cancel\": {\"index\": \"unittest20160810_175547\",\"shard\": 77, \"node\":\"secondary\", \"allow_primary\":true}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"cancel\": {\"index\": \"unittest20160810_175547\",\"shard\": 84, \"node\":\"secondary\", \"allow_primary\":true}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"move\": {\"index\": \".kibana\",\"shard\": 0,\"from_node\": \"secondary\",\"to_node\": \"spot_C4D2B23E\"}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"move\": {\"index\": \"repo20160225_224705\",\"shard\": 2,\"from_node\": \"spot_00C8C755\",\"to_node\": \"spot_01B4ADC5\"}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"move\": {\"index\": \"treeherder20160722_171527\",\"shard\": 12,\"from_node\": \"spot_00C8C755\",\"to_node\": \"spot_01B4ADC5\"}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"move\": {\"index\": \"treeherder20160722_171527\",\"shard\": 13,\"from_node\": \"spot_00C8C755\",\"to_node\": \"spot_01B4ADC5\"}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"move\": {\"index\": \"treeherder20160722_171527\",\"shard\": 14,\"from_node\": \"spot_00C8C755\",\"to_node\": \"spot_01B4ADC5\"}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"move\": {\"index\": \"treeherder20160722_171527\",\"shard\": 15,\"from_node\": \"spot_00C8C755\",\"to_node\": \"spot_01B4ADC5\"}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"move\": {\"index\": \"treeherder20160722_171527\",\"shard\": 17,\"from_node\": \"spot_00C8C755\",\"to_node\": \"spot_01B4ADC5\"}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"move\": {\"index\": \"treeherder20160722_171527\",\"shard\": 25,\"from_node\": \"spot_00C8C755\",\"to_node\": \"spot_01B4ADC5\"}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"move\": {\"index\": \"treeherder20160722_171527\",\"shard\": 26,\"from_node\": \"spot_00C8C755\",\"to_node\": \"spot_01B4ADC5\"}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"move\": {\"index\": \"treeherder20160722_171527\",\"shard\": 1,\"from_node\": \"spot_00C8C755\",\"to_node\": \"spot_BAC8AE00\"}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"move\": {\"index\": \"treeherder20160722_171527\",\"shard\": 2,\"from_node\": \"spot_BAC8AE00\",\"to_node\": \"spot_01B4ADC5\"}}]}"
resources/scripts/es_move_shard.sh:curl -XPOST http://localhost:9200/_cluster/reroute -d"{\"commands\":[{\"move\": {\"index\": \"treeherder20160722_171527\",\"shard\": 0,\"from_node\": \"spot_00C8C755\",\"to_node\": \"spot_00C8C755\"}}]}"
resources/scripts/es_test.sh:curl -XPOST http://localhost:9200/unittest/_search -d "{\"fields\":[\"etl.id\"],\"query\": {\"match_all\": {}},\"from\": 0,\"size\": 1}"
resources/scripts/speedtest.bat:curl -XPOST http://activedata.allizom.org:9200/unittest/_search  -d "{\"aggs\":{\"_match\":{\"range\":{\"ranges\":[{\"to\":1474329600,\"from\":1474243200},{\"to\":1474416000,\"from\":1474329600},{\"to\":1474502400,\"from\":1474416000},{\"to\":1474588800,\"from\":1474502400},{\"to\":1474675200,\"from\":1474588800},{\"to\":1474761600,\"from\":1474675200},{\"to\":1474848000,\"from\":1474761600},{\"to\":1474934400,\"from\":1474848000},{\"to\":1475020800,\"from\":1474934400},{\"to\":1475107200,\"from\":1475020800},{\"to\":1475193600,\"from\":1475107200},{\"to\":1475280000,\"from\":1475193600},{\"to\":1475366400,\"from\":1475280000},{\"to\":1475452800,\"from\":1475366400},{\"to\":1475539200,\"from\":1475452800},{\"to\":1475625600,\"from\":1475539200},{\"to\":1475712000,\"from\":1475625600},{\"to\":1475798400,\"from\":1475712000},{\"to\":1475884800,\"from\":1475798400},{\"to\":1475971200,\"from\":1475884800},{\"to\":1476057600,\"from\":1475971200},{\"to\":1476144000,\"from\":1476057600},{\"to\":1476230400,\"from\":1476144000},{\"to\":1476316800,\"from\":1476230400},{\"to\":1476403200,\"from\":1476316800},{\"to\":1476489600,\"from\":1476403200},{\"to\":1476576000,\"from\":1476489600},{\"to\":1476662400,\"from\":1476576000},{\"to\":1476748800,\"from\":1476662400},{\"to\":1476835200,\"from\":1476748800}],\"field\":\"etl.timestamp\"}},\"_missing\":{\"filter\":{\"or\":[{\"or\":[{\"range\":{\"etl.timestamp\":{\"lt\":1474243200}}},{\"range\":{\"etl.timestamp\":{\"gte\":1476835200}}}]},{\"missing\":{\"field\":\"etl.timestamp\"}}]}}},\"size\":0}"
resources/scripts/speedtest.bat:curl -XPOST http://54.149.35.214:9200/unittest/_search  -d "{\"aggs\":{\"_match\":{\"range\":{\"ranges\":[{\"to\":1474329600,\"from\":1474243200},{\"to\":1474416000,\"from\":1474329600},{\"to\":1474502400,\"from\":1474416000},{\"to\":1474588800,\"from\":1474502400},{\"to\":1474675200,\"from\":1474588800},{\"to\":1474761600,\"from\":1474675200},{\"to\":1474848000,\"from\":1474761600},{\"to\":1474934400,\"from\":1474848000},{\"to\":1475020800,\"from\":1474934400},{\"to\":1475107200,\"from\":1475020800},{\"to\":1475193600,\"from\":1475107200},{\"to\":1475280000,\"from\":1475193600},{\"to\":1475366400,\"from\":1475280000},{\"to\":1475452800,\"from\":1475366400},{\"to\":1475539200,\"from\":1475452800},{\"to\":1475625600,\"from\":1475539200},{\"to\":1475712000,\"from\":1475625600},{\"to\":1475798400,\"from\":1475712000},{\"to\":1475884800,\"from\":1475798400},{\"to\":1475971200,\"from\":1475884800},{\"to\":1476057600,\"from\":1475971200},{\"to\":1476144000,\"from\":1476057600},{\"to\":1476230400,\"from\":1476144000},{\"to\":1476316800,\"from\":1476230400},{\"to\":1476403200,\"from\":1476316800},{\"to\":1476489600,\"from\":1476403200},{\"to\":1476576000,\"from\":1476489600},{\"to\":1476662400,\"from\":1476576000},{\"to\":1476748800,\"from\":1476662400},{\"to\":1476835200,\"from\":1476748800}],\"field\":\"etl.timestamp\"}},\"_missing\":{\"filter\":{\"or\":[{\"or\":[{\"range\":{\"etl.timestamp\":{\"lt\":1474243200}}},{\"range\":{\"etl.timestamp\":{\"gte\":1476835200}}}]},{\"missing\":{\"field\":\"etl.timestamp\"}}]}}},\"size\":0}"

**Comment by klahnakoski** [comment]
I do not know why you would be interested in all usages of POST; I assume you may be thinking they have the potential to be wrong; you need not worry about what is wrong until it is proven wrong.  There is only one line proven wrong:

**Comment by maggienj** [comment]
Agreed. I do not know which file to touch to make this change and test.

**Comment by klahnakoski** [comment]
`app.py` is the main web service entry point.  The `app.add_url_rule()` are mapping HTTP request types to a particular function.  For example this line:

    app.add_url_rule('/query', None, query, defaults={'path': ''}, methods=['GET', 'POST'])

Says map any GET or POST request to `/query` to the `query` function; plus provide a `path` parameter.
[see more here](flask.pocoo.org/docs/0.12/api/)

ActiveData accepts web requests from clients; performs query translation; makes requests to ElasticSearch to get the result; and translates the result to respond to the client.

**Comment by klahnakoski** [comment]
To help explore code be sure you have an IDE that will allow to to "show definition" with a key combination. This will allow you to lookup functions, like `add_url_rule`, without resorting to web lookups

**Comment by klahnakoski** [comment]
I believe this is done too
